### PR TITLE
feat(ui): readable transaction log

### PR DESCRIPTION
**Pull request by delaaxe**

### CODE REVIEW

**Review by dhruvkelawala — COMMENTED** [review]
https://user-images.githubusercontent.com/50968441/170239034-c3a9f1df-aad8-4018-82de-41881919be11.mov

This behaviour doesn't look good to me. I think we should stick with current behaviour unless we are able to extract `message` field

**Comment by delaaxe** [comment]
before PR:
image

after PR:

https://user-images.githubusercontent.com/1091900/170240416-243fb653-b3b9-40c0-98a5-bae5c008aa10.mov


how are you building your failed transaction?

**Comment by dhruvkelawala** [comment]
This is my failed transaction log **before PR**
https://user-images.githubusercontent.com/50968441/170241134-30583a54-91bb-44a5-acf9-64a302731d57.mov

**Comment by delaaxe** [comment]
that's the same video as your first one.

how are you building your failed transaction?

**Pull request closed without merging**
