### PR TITLE
fix: multisig feature flag

### PR DESCRIPTION
**Pull request by dhruvkelawala**
### Issue / feature description

Fixes feature flag in NewAccountScreen

### CODE REVIEW

**Comment by dhruvkelawala** [comment]
Missed a conditional to check for `enabled` even when it was already present

**Comment by simonheys** [comment]
Now it's hidden, but it doesn’t show if I set `FEATURE_MULTISIG=true` - wondered if `const value = process.env[name]` was the culprit

**Comment by dhruvkelawala** [comment]
Fixed

**Comment by dhruvkelawala** [comment]
Copilot suggested me to use `process.env[name]`. Guess it's not correct

**Comment by simonheys** [comment]
> Guess it's not correct always

Copilot = Subtle bug generator :)

**Review by simonheys — APPROVED** [review]

**Pull request merged**
