### PR TITLE
Starknet v3 integration

### PR DESCRIPTION
**Pull request by gergold**

### CODE REVIEW

**Review by delaaxe — CHANGES_REQUESTED** [review]

**Comment by dhruvkelawala** [comment]
Will this release break the code for those who are still on starknet.js v2.x using signer interface?

**Comment by delaaxe** [comment]
> Will this release break the code for those who are still on starknet.js v2.x using signer interface?

Here is a work in progress of a migration document: https://github.com/argentlabs/argent-x/blob/feature/starknet-v3-integration/docs/Upgrade_v3.md

**Comment by dhruvkelawala** [comment]
> > Will this release break the code for those who are still on starknet.js v2.x using signer interface?
> 
> Here is a work in progress of a migration document: https://github.com/argentlabs/argent-x/blob/feature/starknet-v3-integration/docs/Upgrade_v3.md

But will the wallet update automatically for users of ArgentX 2.x? If that happens, the dapps will break until they move to starknet.js v3

**Review by delaaxe — APPROVED** [review]

**Comment by delaaxe** [comment]
> > > Will this release break the code for those who are still on starknet.js v2.x using signer interface?
> > 
> > 
> > Here is a work in progress of a migration document: https://github.com/argentlabs/argent-x/blob/feature/starknet-v3-integration/docs/Upgrade_v3.md
> 
> But will the wallet update automatically for users of ArgentX 2.x? If that happens, the dapps will break until they move to starknet.js v3

Good point, created this issue for it: https://github.com/argentlabs/argent-x/issues/360

**Pull request merged**
