### PR TITLE
Feat/new signing screen

### PR DESCRIPTION
**Pull request by dhruvkelawala**

### CODE REVIEW

**Comment by dhruvkelawala** [comment]
TODO:

- [ ] FeeEstimation Error UI
- [ ] JediSwap Review
- [ ] NFT Trade Review

**Comment by janek26** [comment]
Bildschirm­foto 2023-01-10 um 12 33 39
Bildschirm­foto 2023-01-10 um 12 33 47

please adopt:
- paddings (body and around buttons)
- confirm button color

**Comment by dhruvkelawala** [comment]
Done

**Review by janek26 — APPROVED** [review]
nice! thanks

**Comment by dhruvkelawala** [comment]
Screenshot 2023-01-10 at 12 25 34

**Pull request merged**
